# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet tool install -g JetBrains.dotCover.GlobalTool
  displayName: 'Install dotCover'

- script: dotnet dotcover test --configuration $(buildConfiguration) --output dotcover.html
  displayName: 'Generate code coverage report'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)'
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'dotCover'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*.html'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish code coverage results'
